@paymentToken = UjZ2YKSIt03mi3NcfgvIPoTGXVYmdl
###
GET  {{baseUrl}}payment/create_access_token
Access-Token: {{accessToken}}
User-id: {{userId}}
###
GET {{baseUrl}}payment/payment_request?access_token={{paymentToken}}&userid={{userId}}&course_id=11&coupon=TARGET10
Access-Token: {{accessToken}}
User-id: {{userId}}
###
GET {{baseUrl}}insta/check_mobile_status?payment_id=
Access-Token: {{accessToken}}
User-id: {{userId}}
###
GET {{baseUrl}}home/get_payments
Access-Token: {{accessToken}}
User-id: {{userId}}
###
POST {{baseUrl}}/payment/coupon_apply
Access-Token: {{accessToken}}
User-id: {{userId}}
Content-Type: application/json

{
  "coupon": "TARGET10",
  "course_id": 35
}
###
POST {{baseUrl}}/payment/coupon_remove
Access-Token: {{accessToken}}
User-id: {{userId}}
Content-Type: application/json

{
  "coupon": "TARGET10"
}


# {
#   "access_token": "Huvf0kfGPOnCzdW4gQm7e3ilumq7zi",
#   "expires_in": 36000,
#   "token_type": "Bearer",
#   "scope": "payouts:read payments:read payments:fulfil payments:refund users:read users:write payment-requests:read payment-requests:write gateway-orders:read gateway-orders:write convenience-fee:read"
# }